### ISSUE TITLE
On mentioned vulnerabilities

### ISSUE THREAD

**Issue by Axkaban** [Cais/jammming#1]
To update the vulnerabilities from the message you received, you can usually run `npm audit`.
it will check for those vulnerabilities, find the update, and then you can run the install of the new updates, sometimes running `npm audit fix` does it for you, it seems like this time it requires you to do it manually, the main issue is that as you may see when running `npm audit`, both dependencies are used by surge, and therefore they are the ones that need to fix it, so do not worry for now. You may reinstall surge to check if it has been updated and fixed.

**Comment by Cais** [comment]
Unfortunately, `npm audit fix` did not automatically correct the issue. I was able to locate and find the necessary node modules that needed updating and manually corrected the `package.json` file to account for them.
